### ISSUE TITLE
Error adding frame to DB

### ISSUE THREAD

**Issue by dbarry9** [fdac18/VideoFileUniqueness#16]
python3 driver.py ~/
Traceback (most recent call last):
  File "driver.py", line 45, in <module>
    addDB_Frame(dbref, idno, str(0), rs, gs, bs, res, ims)
  File "/home/dbarry/VideoFileUniqueness/src/storage.py", line 62, in addDB_Frame
    newFrame[0] = newName
IndexError: list assignment index out of range

----------------------------
It seems that the storage module tries to assign values to uninitialized places in an array.

**Comment by nschwerz** [comment]
Fixed,

**Comment by dbarry9** [comment]
python3 driver.py ~/
Traceback (most recent call last):
  File "driver.py", line 45, in <module>
    addDB_Frame(dbref, idno, str(0), rs, gs, bs, res, ims)
  File "/home/dbarry/VideoFileUniqueness/src/storage.py", line 64, in addDB_Frame
    newFrame = newFrame + newRedArr + newGrnArr + newBluArr + newReals + newImags
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

------------------------
I now see this. Is this due to concatentation not being defined by '+'?
